import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | RE:LOOP",
  description: "Terms of use and prototype software disclaimer for RE:LOOP.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8">
      {/* Header */}
      <div className="border-b border-[#d8ddd7] pb-4 space-y-1">
        <div className="flex items-center gap-2 font-mono text-xs text-[#6b746e]">
          <Link href="/" className="hover:text-[#151817] transition-colors">
            &larr; Return Home
          </Link>
          <span>|</span>
          <span>LEGAL &amp; COMPLIANCE</span>
        </div>
        <h1 className="text-3xl font-bold font-display text-[#151817]">
          Terms of Service
        </h1>
        <p className="text-xs text-[#6b746e] font-mono">
          Last updated: October 2026 · Software disclaimer
        </p>
      </div>

      {/* Main Content Sections */}
      <div className="space-y-6 text-sm leading-relaxed text-[#151817]">
        {/* Prototype Banner */}
        <div className="rounded-sm border border-[#a3512b]/30 bg-[#fff2ed] p-5 space-y-2">
          <div className="flex items-center gap-2 font-semibold text-xs text-[#a3512b] uppercase tracking-wider">
            <span className="h-2 w-2 rounded-full bg-[#a3512b]" />
            Prototype Software Notice
          </div>
          <p className="text-xs text-[#151817] leading-relaxed">
            RE:LOOP is an experimental hackathon prototype provided strictly on an &ldquo;AS-IS&rdquo; and &ldquo;AS-AVAILABLE&rdquo; basis without warranties of any kind.
          </p>
        </div>

        <section className="rounded-sm border border-[#d8ddd7] bg-white p-6 space-y-4">
          <h2 className="text-lg font-bold font-display text-[#151817]">
            1. Estimates Are Not Professional Valuations
          </h2>
          <p className="text-xs text-[#6b746e] leading-relaxed">
            All numerical figures generated by the RE:LOOP platform (including Estimated Resale Values in ₹, Estimated Repair Costs in ₹, Post-Purchase Repairability Index [PP-RI] scores, and Embodied Carbon [kg CO2e] savings) are algorithmic estimates derived from statistical baseline models.
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-[#151817] pl-2">
            <li>
              Estimates do not constitute formal appraisals, certified resale guarantees, or binding commercial offers.
            </li>
            <li>
              Actual repair quotes, resale prices, and scrap buyback rates will vary based on physical technician inspection and local market dynamics.
            </li>
          </ul>
        </section>

        <section className="rounded-sm border border-[#d8ddd7] bg-white p-6 space-y-4">
          <h2 className="text-lg font-bold font-display text-[#151817]">
            2. Destination Partners &amp; External Nodes
          </h2>
          <p className="text-xs text-[#6b746e] leading-relaxed">
            RE:LOOP indexes verified third-party destination partners (repair clinics, certified e-waste aggregators, informal kabadiwala clusters, and community NGOs).
          </p>
          <ul className="list-disc list-inside space-y-1.5 text-xs text-[#151817] pl-2">
            <li>
              RE:LOOP does not operate or directly manage third-party destination facilities.
            </li>
            <li>
              Users are responsible for confirming operating hours, drop-off eligibility, and commercial terms directly with partners prior to hardware handoff.
            </li>
          </ul>
        </section>

        <section className="rounded-sm border border-[#d8ddd7] bg-white p-6 space-y-4">
          <h2 className="text-lg font-bold font-display text-[#151817]">
            3. Limitation of Liability
          </h2>
          <p className="text-xs text-[#6b746e] leading-relaxed">
            To the maximum extent permitted by applicable law, RE:LOOP and its contributors shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use this prototype platform.
          </p>
        </section>

        <section className="rounded-sm border border-[#d8ddd7] bg-white p-6 space-y-2">
          <h2 className="text-lg font-bold font-display text-[#151817]">
            4. Open Modification &amp; License
          </h2>
          <p className="text-xs text-[#6b746e] leading-relaxed">
            The mathematical decision engine, PP-RI scoring weights, and UI components are shared for circular economy research and evaluation.
          </p>
        </section>
      </div>

      <div className="pt-4 flex items-center justify-between border-t border-[#d8ddd7]">
        <Link
          href="/"
          className="inline-flex items-center justify-center rounded-sm border border-[#d8ddd7] bg-white px-4 py-2 text-xs font-medium text-[#151817] transition-colors hover:bg-[#e9ede7]"
        >
          &larr; Back to Overview
        </Link>
        <Link
          href="/privacy"
          className="inline-flex items-center justify-center rounded-sm bg-[#2e7d57] px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-[#246644]"
        >
          View Privacy Policy &rarr;
        </Link>
      </div>
    </div>
  );
}
