/**
 * PS-013 Central Civic Status Translation & Language Helper
 * Converts backend database enums into human-centered civic labels and semantic colors.
 * Frontend presentation layer only — does NOT modify backend database values.
 */

export type SemanticStatusVariant = "neutral" | "info" | "warning" | "success" | "danger" | "accent";

export interface StatusMeta {
  raw: string;
  label: string;
  description: string;
  variant: SemanticStatusVariant;
  badgeClass: string;
}

export const REQUEST_STATUS_MAP: Record<string, { label: string; description: string; variant: SemanticStatusVariant }> = {
  pending: {
    label: "Pickup Requested",
    description: "Logged in municipal registry, awaiting dispatch planning.",
    variant: "warning",
  },
  scheduled: {
    label: "Pickup Scheduled",
    description: "Allocated to upcoming municipal collection cycle.",
    variant: "info",
  },
  assigned: {
    label: "Collector Assigned",
    description: "Vehicle manifest confirmed, collector assigned for pickup.",
    variant: "info",
  },
  in_progress: {
    label: "Collection In Route",
    description: "Vehicle is currently executing collection route in your zone.",
    variant: "accent",
  },
  collected: {
    label: "E-Waste Collected",
    description: "Doorstep handover verified at physical scale.",
    variant: "success",
  },
  weighed: {
    label: "Weight Certified",
    description: "Calibrated digital scale verification logged in manifest.",
    variant: "success",
  },
  sent_to_facility: {
    label: "Sent for Recovery",
    description: "Dispatched to accredited recycling or refurbishment facility.",
    variant: "accent",
  },
  recovered: {
    label: "Recovery Recorded",
    description: "Processed at certified facility with circular mass balance.",
    variant: "success",
  },
  cancelled: {
    label: "Request Cancelled",
    description: "Collection request cancelled.",
    variant: "neutral",
  },
  deferred: {
    label: "Pickup Rescheduled",
    description: "Rescheduled due to vehicle payload capacity limits.",
    variant: "warning",
  },
};

export const ROUTE_STATUS_MAP: Record<string, { label: string; description: string; variant: SemanticStatusVariant }> = {
  planned: {
    label: "Route Planned",
    description: "Generated by CVRP heuristic, pending dispatch confirmation.",
    variant: "neutral",
  },
  assigned: {
    label: "Route Assigned",
    description: "Assigned to vehicle driver manifest.",
    variant: "info",
  },
  in_progress: {
    label: "Route Active",
    description: "Driver is currently navigating and collecting stops.",
    variant: "accent",
  },
  completed: {
    label: "Route Completed",
    description: "All stops served and vehicle returned to depot.",
    variant: "success",
  },
  cancelled: {
    label: "Route Cancelled",
    description: "Route itinerary cancelled.",
    variant: "neutral",
  },
};

const VARIANT_BADGE_CLASSES: Record<SemanticStatusVariant, string> = {
  neutral: "bg-[#e9ede7] text-[#6b746e] border-[#d8ddd7]",
  info: "bg-[#e8f1f5] text-[#1c556e] border-[#c2d9e5]",
  warning: "bg-[#fef6e9] text-[#8a5b16] border-[#f4ddb5]",
  success: "bg-[#e6f2e8] text-[#246644] border-[#b8dcbf]",
  danger: "bg-[#fbeeed] text-[#93342d] border-[#f0c3bf]",
  accent: "bg-[#ebf3ed] text-[#173d2c] border-[#9ec4ad]",
};

/**
 * Returns user-facing civic metadata for any collection request status.
 */
export function getRequestStatusMeta(status: string | null | undefined): StatusMeta {
  const normalized = (status || "pending").toLowerCase().trim();
  const entry = REQUEST_STATUS_MAP[normalized] || {
    label: formatRawKeyToCivic(normalized),
    description: "Status recorded in registry.",
    variant: "neutral" as SemanticStatusVariant,
  };

  return {
    raw: normalized,
    label: entry.label,
    description: entry.description,
    variant: entry.variant,
    badgeClass: VARIANT_BADGE_CLASSES[entry.variant],
  };
}

/**
 * Returns user-facing civic metadata for any collection route status.
 */
export function getRouteStatusMeta(status: string | null | undefined): StatusMeta {
  const normalized = (status || "planned").toLowerCase().trim();
  const entry = ROUTE_STATUS_MAP[normalized] || {
    label: formatRawKeyToCivic(normalized),
    description: "Route status recorded.",
    variant: "neutral" as SemanticStatusVariant,
  };

  return {
    raw: normalized,
    label: entry.label,
    description: entry.description,
    variant: entry.variant,
    badgeClass: VARIANT_BADGE_CLASSES[entry.variant],
  };
}

/**
 * Formats a raw snake_case or SCREAMING_SNAKE string into Title Case words.
 */
export function formatRawKeyToCivic(raw: string): string {
  if (!raw) return "";
  return raw
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}
